### ISSUE TITLE
Implementar métricas dinâmicas  dos repositórios do github 

### ISSUE THREAD

**Issue by joaquimsn** [DP6/dp6.github.io#1]
Para obter a quantidade de estrelas  e forks de forma dinâmicas de forma simples, recomendo a utilização do https://shields.io/

## penguin-datalayer-collect
<a href="https://github.com/DP6/penguin-datalayer-collect/stargazers"><img alt="GitHub stars" src="https://img.shields.io/github/stars/DP6/penguin-datalayer-collect?style=social"></a>

<a href="https://github.com/DP6/penguin-datalayer-collect/network"><img alt="GitHub forks" src="https://img.shields.io/github/forks/DP6/penguin-datalayer-collect?style=social"></a>

## analytics-helper
<a href="https://github.com/DP6/analytics-helper/stargazers"><img alt="GitHub stars" src="https://img.shields.io/github/stars/DP6/analytics-helper?style=social"></a>

<a href="https://github.com/DP6/analytics-helper/network"><img alt="GitHub forks" src="https://img.shields.io/github/forks/DP6/analytics-helper?style=social"></a>

No print abaixo podemos notar que os números estão fixos
![image](https://user-images.githubusercontent.com/6219022/111385534-b6c5f400-8689-11eb-84c7-b53fdee247a0.png)

**Comment by 1cadumagalhaes** [comment]
Entender porque o liquid não funcionou corretamente:
```
{{repository.stargazers_count}} <i class="fa fa-star"></i>&nbsp;&nbsp;
{{repository.watchers_count}} <i class="fa fa-eye"></i>
 ```

**Comment by joaquimsn** [comment]
@1cadumagalhaes , aqui acho que o problema é porque o html só é atulizado na hora do build

**Comment by joaquimsn** [comment]
Com a implementação dessa issue esse problema será resolvido parcialmente https://github.com/DP6/dp6.github.io/issues/12

**Comment by 1cadumagalhaes** [comment]
Aproveitei para usar as badges sugeridas no shield.io. 
Encerrando essa issue
