### ISSUE TITLE
Ajustar nomes dos banners para SEO

### ISSUE THREAD

**Issue by joaquimsn** [DP6/dp6.github.io#2]
Os títulos dos banners do site são fictícios, esses valores já estão sendo indexados nos buscadores

![image](https://user-images.githubusercontent.com/6219022/111385809-158b6d80-868a-11eb-92c6-7f7891bc8d9c.png)

![image](https://user-images.githubusercontent.com/6219022/111385854-220fc600-868a-11eb-9ebf-31256933fb65.png)

**Comment by 1cadumagalhaes** [comment]
Banners atualizados
