### ISSUE TITLE
Ajustar carrossel com posts do blog.

### ISSUE THREAD

**Issue by eBetcel** [DP6/dp6.github.io#36]
Atualmente o carrossel com banners do blog está com um comportamento que a página scrolla ao clicar para avançar.
É necessário mudar o comportamento para apenas o banner passar, mas a tela não rolar, quando for apertada a seta do carrossel.

**Comment by 1cadumagalhaes** [comment]
Com a mudança de layout (#37) isso não vai ser mais necessário
