### ISSUE TITLE
Acessibilidade, melhores práticas e SEO

### ISSUE THREAD

**Issue by 1cadumagalhaes** [DP6/dp6.github.io#7]
Ajustar cores, tags de título, labels e descrições nos links e imagens.
![image](https://user-images.githubusercontent.com/40048825/112008280-17c74f00-8b04-11eb-89ba-aa81cdb725cb.png)

**Comment by 1cadumagalhaes** [comment]
Também acrescentar o favicon no site

**Comment by joaquimsn** [comment]
Melhorias de SEO e performance implementadas.

[performance-dp6.github.io-mobile.pdf](https://github.com/DP6/dp6.github.io/files/6321439/performance-dp6.github.io-mobile.pdf)
[performance-dp6.github.io-desktop.pdf](https://github.com/DP6/dp6.github.io/files/6321447/performance-dp6.github.io-desktop.pdf)

**Comment by joaquimsn** [comment]
![image](https://user-images.githubusercontent.com/6219022/114946713-18f94c80-9e22-11eb-90f1-f35bda9982c3.png)
